name: Docker Test Running

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest    
    container:
      image: ghcr.io/balajiselvaraj1601/sample_docker_1
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
         
    steps:
    - name: Download code to Docker
      uses: actions/checkout@v3
    - name: Run the Docker image
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv) 
    - name: Run the code inside docker
      run: python app_file.py
