
name: Docker Image CI

on:
  workflow_dispatch
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login with Github Container registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to Github Container registry
      run: |
            cd ./tmp_dockerfile
            echo "$PWD"
            docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/sample_docker_1:latest
            docker push ghcr.io/${{ github.actor }}/sample_docker_1:latest
