name: Label Checker

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if Issue has Labels
        if: github.event.action == 'closed'
        run: |
          if: ${{ contains(fromJson('["bug", "documentation", "enhancement"]'), github.event.label.name) == false }}; then
            echo "Label Check: Failure. Reopening the issue."
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -d '{"state": "open"}'            
          else
            echo "Label Check: Success"
          fi
