name: Label Checker

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if Issue has Labels
        if: github.event.action == 'closed'
        run: |
          if: ${{ contains(fromJson('["bug", "documentation", "enhancement"]'), github.event.label.name) == false }}; then
            echo "Label Check: Failure. Reopening the issue."
          else
            echo "Label Check: Success"
          fi
