name: Label Checker

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if Issue has Labels
        run: |
          # Extract the labels from the closed issue
          labels=$(echo "${{ toJson(github.event.issue.labels) }}" | sed 's/[{}]//g' | tr ',' '\n' | sed 's/."name": "//g' | sed 's/".//')
          
          # Define the required labels
          required_labels=("bug" "documentation" "enhancement")
    
          # Check if any of the required labels are present
          label_found=false
          for label in "${required_labels[@]}"; do
            if [[ " ${labels[@]} " =~ " $label " ]]; then
              label_found=true
              break
            fi
          done
    
          # If no required labels are found, reopen the issue
          if [ "$label_found" = false ]; then
            echo "Label Check: Failure. Reopening the issue."
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -d '{"state": "open"}'
          else
            echo "Label Check: Success"
          fi
